import os from 'os';
import path from 'path';

export interface CollectorConfig {
  httpPort: number;
  grpcPort: number;
  logsFilePath: string;
  metricsFilePath: string;
  sessionId?: string;
}

/**
 * Generate OpenTelemetry Collector YAML configuration
 */
export function generateCollectorConfig(config: CollectorConfig): string {
  const { httpPort, grpcPort, logsFilePath, metricsFilePath } = config;

  return `# OpenTelemetry Collector Configuration
# Generated by claude-companion

receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:${httpPort}
      grpc:
        endpoint: localhost:${grpcPort}

exporters:
  # File exporter for logs/events
  file/logs:
    path: ${logsFilePath}
    rotation:
      max_megabytes: 10
      max_days: 7
      max_backups: 3

  # File exporter for metrics
  file/metrics:
    path: ${metricsFilePath}
    rotation:
      max_megabytes: 10
      max_days: 7
      max_backups: 3

  # Debug exporter (optional, for troubleshooting)
  # logging:
  #   loglevel: debug

processors:
  # Batch processor for better performance
  batch:
    timeout: 1s
    send_batch_size: 100

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/logs]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/metrics]

  # Optional telemetry configuration
  telemetry:
    logs:
      level: info
`;
}

/**
 * Get default paths for collector files
 */
export function getDefaultCollectorPaths(sessionId?: string): {
  collectorDir: string;
  configPath: string;
  logsPath: string;
  metricsPath: string;
  pidPath: string;
  binaryPath: string;
  stdoutPath: string;
  stderrPath: string;
} {
  const homeDir = os.homedir();
  const collectorDir = path.join(homeDir, '.claude-code', 'collector');
  const otelDir = path.join(homeDir, '.claude-code', 'otel');

  const sessionSuffix = sessionId ? `-${sessionId}` : '';

  return {
    collectorDir,
    configPath: path.join(collectorDir, `config${sessionSuffix}.yaml`),
    logsPath: path.join(otelDir, `${sessionId || 'session'}-logs.jsonl`),
    metricsPath: path.join(otelDir, `${sessionId || 'session'}-metrics.jsonl`),
    pidPath: path.join(collectorDir, `collector${sessionSuffix}.pid`),
    binaryPath: path.join(collectorDir, 'otel-collector'),
    stdoutPath: path.join(collectorDir, `collector${sessionSuffix}.stdout.log`),
    stderrPath: path.join(collectorDir, `collector${sessionSuffix}.stderr.log`),
  };
}

/**
 * Get default port configuration
 */
export function getDefaultPorts(): { httpPort: number; grpcPort: number } {
  return {
    httpPort: 4318, // Standard OTLP/HTTP port
    grpcPort: 4317, // Standard OTLP/gRPC port
  };
}
